INSERT INTO Activity (id,name,subject,data) VALUES  (1,'Prova Final', 'Estatistica', '03/11/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (2,'Lista 1', 'Estatistica', '11/08/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (3,'Prova 2', 'Estatistica', '20/09/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (4,'Prova 3', 'Estatistica', '18/10/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (5,'Prova 1', 'Estatistica', '16/08/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (6,'Lista 2', 'Estatistica', '18/10/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (7,'Prova 1', 'Sistema Operacional', '24/08/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (8,'Prova 2', 'Sistema Operacional', '28/09/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (9,'Prova 3', 'Sistema Operacional', '26/10/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (10,'Projeto pratico', 'Sistema Operacional', '06/10/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (11,'Video / Apresentacao', 'Sistema Operacional', '21/10/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (12,'Prova 1', 'Organizacao de Computadores', '31/08/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (13,'Prova 2', 'Organizacao de Computadores', '26/10/2021');
INSERT INTO Activity (id,name,subject,data) VALUES  (14,'Prova 1', 'Matemática Discreta', '16/07/2021');
